### ISSUE TITLE
Delaunay2D

### ISSUE THREAD

**Issue by jacbouzada** [wblut/HE_Mesh2014#21]
Hi WBlut,

Congratulations for your library. It´s amazing. Too big for a newbie like me.
I have a problem working with a delaunay in 2D. Delaunay in 3D works fine, but I can´t get a 2d delaunay graph of a set of points.

For example, if I set z=0 ( point[2]=0) in the example sketch "Ref WB_Delaunay3D" I get a Null error.
Seems like when points are coplanar something doesn't work as I would expected...mmmmmmm

So I tried to write the simplest sketch for a 2D delaunay, and again the problem is that after a "triangulation = WB_Delaunay.getTriangulation2D(points, .1);" I always get a null.
I wrote some code below.

What I am doing wrong?
What does it mean "4d", delaunay4D?

Thank you in advance!

	
	public void setup() {
		size (800,800);
		background(255);
		render = new WB_Render2D(this);
		
		points = new ArrayList<WB_Point>();
		float x, y;
		float r = 250;
		for (int i =0; i < 500; i++){
			x = width/2 + random(-r, r);
			y = height/2 + random(-r, r);
			WB_Point nuevoPunto = new WB_Point (x, y);		
			points.add(nuevoPunto);
		}
		
		triangulation = WB_Delaunay.getTriangulation2D(points, .1);
		
		println(triangulation);
	}

	public void draw() {
		for(WB_Point p : points){
		render.drawPoint(p, 1);
		}
	}
	
	public static void main(String _args[]) {
		PApplet.main(new String[] { delaunay2.Delaunay2.class.getName() });
	}
}

**Comment by wblut** [comment]
Sorry for the confusion. Please use the WB_Triangulate functions, not the WB_Delaunay... Those functions are fickle and I still need to test everything.

So:
'''Java
import wblut.math.*;
import wblut.processing.*;
import wblut.core.*;
import wblut.hemesh.*;
import wblut.geom.*;

WB_Render2D render;
ArrayList<WB_Point> points;
WB_Triangulation2D triangulation;

public void setup() {
    size (800,800,P2D);
    smooth(8);
    background(255);
    render = new WB_Render2D(this);
    points = new ArrayList<WB_Point>();
    float x, y;
    float r = 250;
    for (int i =0; i < 500; i++){
        x = width/2 + random(-r, r);
        y = height/2 + random(-r, r);
        WB_Point nuevoPunto = new WB_Point (x, y);      
        points.add(nuevoPunto);
    }
    triangulation = WB_Triangulate.getTriangulation2D(points);
}

public void draw() {
    background(255);
    for(WB_Point p : points){
      render.drawPoint(p, 2);
    }
    render.drawTriangulationEdges(triangulation, points) ;
}
'''

And 4D is exactly what it means, a Delaunay triangulation of 4D points, returning 4D hypertetrahedra...

**Comment by jacbouzada** [comment]
Thanks for the response, WBlut !!!
It works perfectly!!! 

One useful thing with WB_Delaunay is that, for each vertex, you give me his "Neighbors" in the Delaunay graph, and indeed in a 3D Delaunay works fine. It seems that the WB_Triangulation2D don't have this method.
Any idea? Maybe can I transform the WB_Triangulation2D into a HE_Mesh, and then look for the neighbors of my selected  He_Vertex using the "getNeighborVertices()" method? I´ll try.

and 4D points..., 4D hypertetrahedra...,  new for me, but sounds interesting. I will check ;)

Thanks!
