### ISSUE TITLE
Calling subdividor on selection results in NPE

### ISSUE THREAD

**Issue by AmnonOwed** [wblut/HE_Mesh2014#23]
When you use a subdividor on a selection, it results in a NullPointerException.

Using Hemesh version 2.0.11 Persephone.

Code example that reproduces the bug:

```java
import wblut.math.*;
import wblut.processing.*;
import wblut.core.*;
import wblut.hemesh.*;
import wblut.geom.*;

HE_Mesh mesh = new HE_Mesh(new HEC_Dodecahedron().setEdge(100));
HES_CatmullClark subdividor = new HES_CatmullClark();
HE_Selection selection = mesh.selectAllFaces(); 
subdividor.apply(selection);
//mesh.subdivideSelected(subdividor, selection);
println("Made it.");
exit();
```

**Comment by AmnonOwed** [comment]
I have tested this sketch for all the different subdividors. It seems only **CatmullClark** and **Smooth** result in a NullPointerException, when used in the test sketch above. Additional information:

- HES_CatmullClark: NPE
- HES_DooSabin: works
- HES_Planar: works
- HES_PlanarMidEdge: works
- HES_Smooth: NPE

**Comment by AmnonOwed** [comment]
It looks like [this line](https://github.com/wblut/HE_Mesh2014/blob/master/hemesh/src/wblut/hemesh/HES_Smooth.java#L156) is the culprit:
```java
selection.parent.splitFacesQuad(selection);
```

**Comment by AmnonOwed** [comment]
Tracked it down. When you follow the bug all the way to the source, the end of the line is [this](https://github.com/wblut/HE_Mesh2014/blob/580b4689686878cd0fc5fa219031ffc95b9dc82a/hemesh/src/wblut/hemesh/HEM_QuadSplit.java#L124) one:

```java
if (he2[c].getVertex().hasHalfedgeTexture(f)) {
```

**Comment by wblut** [comment]
Fixed in the repository. It was a combination of typos in the code (that *f* should've been *face*) and an inherent problem with the texture system.
