### ISSUE TITLE
getData() may lead to NullPointerException

### ISSUE THREAD

**Issue by AmnonOwed** [wblut/HE_Mesh2014#24]
All classes that implement the WB_HasData Interface use a straightforward getData() method that results in a NullPointerException when the _data HashMap is not initialized. Below is a small code example that replicates the problem. While in this code example it's fairly obvious, this behavior also occurs for example when there is any kind of subdivision (or similar), since the new vertices do not have the data. Currently the program crashes with a NPE. It would be more useful to return null in the case there is no data (read: no HashMap), because then it could be handled gracefully by the user program. I have included a proposed fix below, which I think would solve the problem.

**Code Example**

```java
import wblut.math.*;
import wblut.processing.*;
import wblut.hemesh.*;
import wblut.geom.*;

HE_Mesh mesh = new HE_Mesh(new HEC_Dodecahedron().setEdge(200));
HE_Vertex v = mesh.vertices.get(0);
//v.setData("trying", "something");
Object o = v.getData("trying");
println(o);
println("Done");
exit();
```

**Proposed Fix**

```java
public Object getData(final String s) {
  if (_data != null) {
    return _data.get(s);
  } else {
    return null;
  }
}
```

**Comment by wblut** [comment]
True, fixed in the repo. Thanks for testing, hoping to have some time again in the next few months.

**Comment by AmnonOwed** [comment]
Noticed there's another [in the WB_AABB class](https://github.com/wblut/HE_Mesh2014/blob/master/hemesh/src/wblut/geom/WB_AABB.java#L1098-L1100), which also doesn't formally implement WB_HasData.
