### ISSUE TITLE
Thread safety in HE_Mesh

### ISSUE THREAD

**Issue by AmnonOwed** [wblut/HE_Mesh2014#25]
I've been working on threaded creation and manipulation of a HE_Mesh and threaded creation of a PShape. I works pretty well for 99%. Mesh creation and all kind of manipulations seem to work without issues. I only ran into one problem with PShape creation, specifically with the triangulation that is needed for the TRIANGLES in the PShape. This led me to do some extensive testing...

I've recreated the problem/symptom in the stripped example sketch posted below. As usual with threaded problems, they're kind of unpredictable and thus hard to debug. It's basically the combination of creation, display and triangulation of a copy (!) of the mesh that is causing problems. Since creation and display are required in my actual program and delay is not a solid workaround (it sometimes works, but not always), I'm still looking for a more solid solution.

My current workaround is to do the triangulation on the 'meshForPShape' outside the thread, which is obviously reintroducing the kind of slowdown I was trying to prevent.

Would like to hear your take on this. What might be causing this, what could be a solution? To what 
extent is HE_Mesh (meant to be) thread-safe?

HE_Mesh version: W:Blut HE_Mesh 2.0.13 Persephone

_**Notes on running the example sketch:** Running the example will quickly lead to different possible errors (IndexOutOfBoundsException, ArrayIndexOutOfBoundsException, NegativeArraySizeException). Indications of apparantly non-thread-safe operations somewhere... It will also show visually in both the mesh and the PShape. Changing any of the settings in the sketch (see comments below) will prevent these problems._

**Code Example:**
```java
/*
 * The main symptom of problems in this example is the triangulate() method in ThreadedPShapeCreator.createPShape(),
 * however after extensive testing, it seems combinations of mesh creation, display and manipulation in HE_Mesh
 * are not entirely thread-safe (even though I got those things 99% working in a threaded manner :-).
 */

import wblut.math.*;
import wblut.processing.*;
import wblut.core.*;
import wblut.hemesh.*;
import wblut.geom.*;

boolean displayMesh = true; // not displaying the mesh, prevents problems
boolean createShape = true; // not recreating the mesh, prevents problems
boolean triangulate = true; // not triangulating a copy (!) of the mesh, prevents problems
int delayTime = 0; // setting a higher delay (100+), decreases the likelihood of problems

WB_Render render;
HE_Mesh mesh;
boolean isThreadActive;
PShape shape;

void setup() {
  size(1280, 720, P3D);
  smooth(8);
  render = new WB_Render(this);
  createMesh();
}

void draw() {

  // UPDATE
  if (!isThreadActive && frameCount % 60 == 0) {
    isThreadActive = true;
    if (createShape) { 
      createMesh();
    }
    new ThreadedPShapeCreator().start();
  }

  // DISPLAY
  background(isThreadActive ? #00FF00 : 125);
  directionalLight(255, 255, 255, 1, 1, -1);
  directionalLight(127, 127, 127, -1, -1, 1);
  translate(width/2, height/2, -100);

  if (displayMesh) {
    pushMatrix();
    translate(-width/4, 0);
    fill(255);
    noStroke();
    render.drawFaces(mesh);
    noFill();
    stroke(0, 75);
    render.drawEdges(mesh);
    popMatrix();
  }

  if (shape != null) {
    pushMatrix();
    translate(width/4, 0);
    shape(shape);
    popMatrix();
  }
}

void createMesh() {
  mesh = new HE_Mesh(new HEC_Dodecahedron().setEdge(200));
}

class ThreadedPShapeCreator extends Thread {

  @Override
  public void run() {
    print("\nThreadedPShapeCreator: start (" + frameCount + ") => ");
    delay(delayTime);
    shape = createPShape(mesh);
    isThreadActive = false;
    print("end (" + frameCount + ")");
  }

  private PShape createPShape(final HE_Mesh mesh) {
    final PShape retained = createShape();
    try {
      HE_Mesh meshForPShape = mesh.get();    
      if (triangulate) {
        meshForPShape.triangulate(); // main symptom
      }
      retained.beginShape(TRIANGLES);
      retained.stroke(0, 75);
      final HE_FaceIterator fItr = meshForPShape.fItr();
      while (fItr.hasNext ()) {
        HE_Face f = fItr.next();
        HE_Halfedge he = f.getHalfedge();
        do {
          HE_Vertex v = he.getVertex();
          retained.fill(v.getColor());
          retained.vertex(v.xf(), v.yf(), v.zf());
          he = he.getNextInFace();
        } 
        while (he != f.getHalfedge ());
      }
      retained.endShape();
    }
    catch (Exception e) {
      e.printStackTrace();
    }
    return retained;
  }
}
```

**Comment by wblut** [comment]
HE_Mesh is not necessarily thread-safe. The problem you encounter is caused by WB_Triangulate. This currently uses static functions and some static temporary data structures.
This is what is causing the errors, both drawFaces and triangulate call the same static function and the shared data structure "shellCoords" gets corrupted. Workaround is to avoid drawFaces while a thread is active...

**Comment by wblut** [comment]
Replacing
```java
render.drawFaces(mesh);
```
with
```java
if(!isThreadActive)render.drawFaces(mesh);
```
works. The permanent solution is of course to allow separate WB_Triangulation objects...

**Comment by wblut** [comment]
Confirmed. Problem disappears if polygon triangulation in WB_Triangulate no longer uses static variables. Updated in current repo.

**Comment by AmnonOwed** [comment]
Great, thanks for the fix!
