### ISSUE TITLE
getClosestPoint ( WB_Point , WB_KDTree<WB_Point,Long> ) 

### ISSUE THREAD

**Issue by jacbouzada** [wblut/HE_Mesh2014#27]
I´m tying to make a sketch with a random walker on the surface of a hemesh surface, using the HE_Mesh method :
`getClosestPoint (final WB_Point p, final WB_KDTree< WB_Point, Long > vertexTree)`

So given any query point like:
`WB_Point randomPoint;`

And given a vertexTree, KD-tree from myMesh (from vertexTree()) that returns a KD-tree containing all vertices.
`WB_KDTree<WB_Coordinate, Long> myVertexTree = mesh.getVertexTree();`

I get trouble trying to make a sentence like this:
`WB_Point myClosestPoint = mesh.getClosestPoint(randomPoint, myVertexTree);`

The problem is that `the method getClosestPoint ( WB_Point , WB_KDTree< WB_Point, Long > ) 
in the type HE_Mesh is not applicable for the arguments WB_KDTree <WB_Coordinate, Long>`

Is there any method like `getVertexTree()` that returns a `WB_KDTree<WB_Point, Long> `,
or how can I translate the `WB_KDTree<WB_Coordinate, Long>` into a `WB_KDTree<WB_Point, Long>`

I´m newbie in Processing and don´t know if this is the best place to make this questions.....do you have any specific HE_Mesh forum? ;)

thank you in advance!

**Comment by vormplus** [comment]
A possible solution is to use the `getNeighborVertices()`method on your vertex and calculate the distance from those points to your current vertex to find the closest one. Working with the KDTree might be memory-expensive if you work with a large mesh.

You can always ask questions about HE_Mesh on the Processing Forum. There are some people there using HE_Mesh. This place is normally used to file bugs.

**Comment by jacbouzada** [comment]
Thank you for your answer Jan. Your HeMesh tutorials are so useful!!! ;)

But I was wondering how to "project" on a surface an external point, out of the mesh surface.
I suppose that the solution of the `getNeighborVertices()` works only for a HE_Vertex into the HE_Mesh.
That´s why I´m looking for methods like `getClosestPoint` and `getClosestVertex`, but I found this problem:  how can I get a `WB_KDTree<WB_Point, Long>` of a mesh or how can I translate the `WB_KDTree<WB_Coordinate, Long>` into a `WB_KDTree<WB_Point, Long>`.

I will post this question in the Processing Forum. ;)

**Comment by jacbouzada** [comment]
I realized that the `getFaceTree()` method gets back a `WB_KDTree <WB_Point, Long> `.
( instead of the `getVertexTree()`that returns a `WB_KDTree<WB_Coordinate, Long>`)
But any query gives a null... 
What I am doing wrong?

For example:
```
public class HeMeshProjectOnSphere extends PApplet {
	
	PeasyCam cam;
	HE_Mesh mesh;
	WB_Render render;
	WB_Point randomPoint;
	WB_Point pointOnFace;
	HE_Vertex pointOnVertex;

	float sizeWorld = 300;

	public void setup() {
		size(800, 800, OPENGL);
		cam = new PeasyCam(this, 500);
		render=new WB_Render(this);
		smooth(8);
		
		HEC_Sphere creator=new HEC_Sphere();
		creator.setRadius(100).setUFacets(32).setVFacets(32);
		mesh=new HE_Mesh(creator); 
		
		randomPoint = new WB_Point(random(sizeWorld), random(sizeWorld), random(sizeWorld));

		// trying to get the projection point on a mesh (face, vertex,...)
		WB_KDTree <WB_Point, Long> myFaceTree = mesh.getFaceTree();
		pointOnFace = mesh.getClosestPoint(randomPoint, myFaceTree);	
		pointOnVertex = mesh.getClosestVertex(randomPoint, myFaceTree);
		
		println(myFaceTree.toString());
		println (pointOnFace);
		println (pointOnVertex);
	}

	public void draw() {
		background(255);
		
		stroke(0,100);
		render.drawEdges(mesh);
		
		stroke(255,10,10);
		render.drawPoint(randomPoint,5);
		if (pointOnFace != null) render.drawPoint(pointOnFace,5);	
		if (pointOnVertex != null) render.drawPoint(pointOnVertex,5);
	}
```

**Comment by wblut** [comment]
Good question, looking into the whole thing. Sorry it took some time to respond. This particualr part of the code has been long unvisited by me...

**Comment by wblut** [comment]
Both functions you require a vertexTree not a faceTree: mesh.getVertexTree(). In the most current repository mesh functions refer to WB_Coordinate as often as possible, some remnants referred to the less general WB_Point. So if you update it will be WB_KDTree<WB_Coordinate, Long> again. CHeers,

F

**Comment by jacbouzada** [comment]
Thanks !!!
