### ISSUE TITLE
fuseCoplanarFaces on a prism created from polygon with a hole

### ISSUE THREAD

**Issue by jmkinzer** [wblut/HE_Mesh2014#31]
The code below produces an NPE as follows. Is this unsupported or a bug? Thanks!
```
       Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at wblut.hemesh.HE_Face.getNeighborFaces(HE_Face.java:618)
	at wblut.hemesh.HE_Mesh.fuseCoplanarFace(HE_Mesh.java:3218)
	at wblut.hemesh.HE_Mesh.fuseCoplanarFaces(HE_Mesh.java:3283)
	at wblut.hemesh.HE_Mesh.fuseCoplanarFaces(HE_Mesh.java:3265)
```

```java
		  WB_GeometryFactory gf=WB_GeometryFactory.instance();	

		  ArrayList<WB_Point> shell, hole;
		  shell= new ArrayList<WB_Point>();
		  for (int i=0; i<20; i++) {
		    shell.add(gf.createPointFromPolar(100*(i%2+1), TWO_PI/20.0*i));
		  }
		  hole= new ArrayList<WB_Point>();
		  for (int i=0; i<10; i++) {
		    hole.add(gf.createPointFromPolar(40*(i%2+1), -TWO_PI/10.*i));
		  } 
		  
		  WB_Polygon polygon=gf.createPolygonWithHole(shell, hole); // not ok
		  //polygon=gf.createSimplePolygon(shell); // ok
		  		  
		  WB_FaceListMesh meshFL = gf.createPrism(polygon, 10);
		  HE_Mesh mesh = new HE_Mesh(meshFL);
			
		  mesh.fuseCoplanarFaces();
```

**Comment by jmkinzer** [comment]
Aha, this approach does work (and already has all coplanar faces merged):

```java
		  WB_GeometryFactory gf=WB_GeometryFactory.instance();	

		  ArrayList<WB_Point> shell, hole;
		  shell= new ArrayList<WB_Point>();
		  for (int i=0; i<21; i++) {
		    shell.add(gf.createPointFromPolar(100*(i%2+1), TWO_PI/20.0*i));
		  }
		  hole= new ArrayList<WB_Point>();
		  for (int i=0; i<11; i++) {
		    hole.add(gf.createPointFromPolar(40*(i%2+1), -TWO_PI/10.*i));
		  } 

		  WB_Polygon polygon=gf.createPolygonWithHole(shell, hole);
		  HEC_Polygon pc = new HEC_Polygon(polygon, 10);
		  mesh = pc.create();
```

Note the difference appears to be this adds an additional 'internal' edge (maybe the other attempt was not manifold - but I though HE_Mesh had to be?)

![image](https://cloud.githubusercontent.com/assets/7916561/9823683/831d7b76-588d-11e5-857e-ad3a35cfad77.png)

**Comment by wblut** [comment]
Faces in hemesh can't have holes. It's an implementation choose, many 
algorithms become wayntoo complex otherwise.

Cheers,

F.



Jason schreef op 2015-09-11 21:01:

**Comment by jmkinzer** [comment]
Gotcha. Stupid follow-up question to make sure I'm clear: in the second case this is not technically a face with a hole - because of the edge circled in blue (i.e. is a concave polygon with an infinitely tiny opening). Is that correct? Thanks!

**Comment by wblut** [comment]
Correct, but I'm not sure how the code handles an edge where both faces 
are the same face, a face that is his own neighbor... Split it in two 
faces to be on the safe side.

Jason schreef op 2015-09-12 02:18:

**Comment by jmkinzer** [comment]
Thanks
