### ISSUE TITLE
HEM_CapHoles causes file corruption

### ISSUE THREAD

**Issue by mohanadHamed** [wblut/HE_Mesh2014#37]
I have a simple cube model with one hole. I am trying to use cap holes modifier to close holes as shown below:

		HE_Mesh mesh;
		HEC_Creator hec = new HEC_FromOBJFile("D:\\sample2.obj");
		mesh = hec.create();

		HEM_CapHoles capHolesModifier = new HEM_CapHoles();
		mesh = mesh.modify(capHolesModifier);

		HET_Export.saveToOBJ(mesh, "D:\\He_Mesh_Models", "output");

Attached the simple cube model that I used as input.

[simple_cube.zip](https://github.com/wblut/HE_Mesh2014/files/74871/simple_cube.zip)

**Comment by wblut** [comment]
Good find, I'm looking into it. Use this as a workaround:

```
HE_Mesh mesh;
HEC_Creator hec = new HEC_FromOBJFile("D:\\sample2.obj");
mesh = hec.create();
mesh.uncapBoundaryHalfedges();
mesh.capHoles();
HET_Export.saveToOBJ(mesh, "D:\\He_Mesh_Models", "output");
```

**Comment by mohanadHamed** [comment]
Thanks alot :)

**Comment by mohanadHamed** [comment]
By the way, using capholes for the attached file seems to make an infinite loop, should I report it as separate issue?


[model_test_3.zip](https://github.com/wblut/HE_Mesh2014/files/75416/model_test_3.zip)
