### ISSUE TITLE
HE_Mesh.capholes() causes an infinite loop

### ISSUE THREAD

**Issue by mohanadHamed** [wblut/HE_Mesh2014#38]
I used the following code to close the holes of attached model:

<pre>
<code>HE_Mesh mesh;
HEC_Creator hec = new HEC_FromOBJFile("D:\\sample2.obj");
mesh = hec.create();
mesh.uncapBoundaryHalfedges();
mesh.capHoles();
HET_Export.saveToOBJ(mesh, "D:\\He_Mesh_Models", "output");
</code></pre>

The problem is that calling capholes() makes an infinite loop.

[sample3_org.zip](https://github.com/wblut/HE_Mesh2014/files/75605/sample3_org.zip)

**Comment by wblut** [comment]
Oh boy, that mesh is a mess ;-)

**Comment by wblut** [comment]
I fixed HEM_CapHoles() so it returns valid meshes. However, HE_Mesh is not a mesh repair tool, so the result is not guaranteed to be a closed mesh.
