### ISSUE TITLE
Boundary edges are not processed correctly 

### ISSUE THREAD

**Issue by mohanadHamed** [wblut/HE_Mesh2014#40]
I need to remove the 48 boundary edges that the attached tire model has. 
I tried HEM_CapHoles modifier but it closed the whole tire. Is there a possible way to cap the boundaries without losing the tire shape?

Thank you for this great library.

[sample26.zip](https://github.com/wblut/HE_Mesh2014/files/85480/sample26.zip)

**Comment by wblut** [comment]
There is no easy solution for this mesh.There are 2 rings of boundary edges but they do not form a "sensible" topology to repair. Vertex snapping might solve the problem but HE_Mesh does not implement this yet.

On the other hand the shape itself is easy to create using HEC_Torus.
