### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by AlbertoG89** [wblut/HE_Mesh2014#41]
Is there a complete documentation somewhere with all classes and methods? 

Thanks for this great library and for the work

**Comment by AlbertoG89** [comment]
The fact is that in the latest built (07/01/2016) the reference folder is empty. Anyway I saw that if I download a previous release there is everything.

**Comment by wblut** [comment]
Yes, due to major cleanup of the reference materials, this is currentky absent.
