### ISSUE TITLE
selectFacesWithOtherInternalLabel(int) missing

### ISSUE THREAD

**Issue by virtualritz** [wblut/HE_Mesh2014#43]
The example https://github.com/wblut/HE_Mesh2014/blob/master/examples/Ref_HEC_FromVoronoiCells/Ref_HEC_FromVoronoiCells.pde doesn't compile (Processing 3.0.1, HE_Mesh 20160207).

The error is:
The function selectFacesWithOtherInternalLabel(int) does not exist.

**Comment by wblut** [comment]
I seem to have some problems getting the examples to sync properly. Although my local copy is reportedly in sync, the examples are clearly not. I've removed and re-added the examples. Should work now. The syntax is no longer `mesh. selectBlah()` but `HE_Selection.selectBlah(mesh)`
