### ISSUE TITLE
ArrayIndexOutOfBoundsException with HEM_ChamferEdges

### ISSUE THREAD

**Issue by nselikoff** [wblut/HE_Mesh2014#44]
Thanks for sharing the awesome library and all the work that's gone into it!

I'm using Processing 3.0.2, HE_Mesh 3.0.2, on OS X 10.11.3. Running the Ref_HEM_ChamferEdges sample gives an `ArrayIndexOutOfBoundsException: 3` on the `mesh.modify(modifier)` line.

**Comment by wblut** [comment]
Thanks Nathan!

Can you check if the error also happens with the latest build-of-the 
day: http://www.wblut.com/#hemesh

Cheers,

F.


Nathan Selikoff schreef op 2016-03-02 16:56:

**Comment by nselikoff** [comment]
Sure thing. It does not happen with the latest build-of-the day. Thanks :)
